#============================================================================
# Make file for TicTacToe
#
# Software Development - Kent State University
#
# Andrew Gast
#
###############################################################
tictactoe-v1.0.cpp: tictactoe-v1.0.o
	g++ tictactoe-v1.0.o -o tictactoe

tictactoe-v1.0.o: tictactoe-v1.0.cpp
	g++ -c tictactoe-v1.0.cpp

###############################################################
#This will clean up everything via "make clean"
clean:
	rm *.o tictactoe

#####################
